name: Run autotest

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Select tests to run'
        required: true
        type: choice
        default: 'all'
        options:
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5   # обнови с v4 → v5
        with:
          chrome-version: 146
          install-chromedriver: true

      - name: Remove any old conflicting chromedriver
        run: |
          sudo rm -f /usr/local/bin/chromedriver /opt/hostedtoolcache/setup-chrome/chromedriver/*/chromedriver || true

      - name: Install Python packages
        run: pip install pytest selenium

      - name: Run tests
        run: xvfb-run -a pytest -v --tb=short
